export interface Person {
    id: number,
    firstName: string,
    lastName: string,
    gender: string,
    dateOfBirth: string,
    insuranceCompany: string,
    mobilePhone: string,
    emailAddress: string,
    identityNumber: string,
    privacyApproval: boolean,
    street: string,
    number: string,
    box: string | null,
    postalCode: string,
    city: string,
    country: string,
    addressType: string,
}
